[package]
name = "sfconversions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extendr-api = "0.4.0"
geo-types = "0.7.9"
